# EternalTags Config | Join support discord if you're having any issues.
# Should the plugin use bstats metrics?
metrics: true

# Should the plugin check for updates on startup?
check-updates: true

# Default tag for players who have joined for the first time.
# Set this to 'None' to disable.
default-tag: 'eternaltags'

# This is the placeholder that will show instead of "None" for placeholder %eternaltags_tag_formatted%
formatted_placeholder: 'None'

# Clear a user's tag if they don't have access to it
remove-inaccessible-tags: false

# Enable if you want to save everything in MySQL
mysql:
  enabled: false
  host: localhost
  port: 3306
  dbname: DBName
  username: Username
  password: Password
  ssl: true
  tablename: eternaltags

# Configure your tags here
tags:
  eternaltags:
    name: 'EternalTags'
    tag: '&7[<r:0.7>EternalTags&7]'
    description:
      - 'The eternaltags tag!'
    permission: 'eternaltags.tag.eternaltags'
    # Used if you want a specific order on your tags and if you have your tag order in tag-menu set to CUSTOM
    order: -1
    # Used if you want a specific icon for the tag, This is not required, You can
    icon: NAME_TAG
  gradient:
    name: 'Gradient'
    tag: '&7[<g:#ED213A:#93291E>Gradient&7]'
    description:
      - 'A very cool gradient!'
    permission: 'eternaltags.tag.gradient'
  animatedRainbow:
    name: 'AnimatedRainbow'
    tag: '&7[<r#10:0.7>AnimatedRainbow&7]'
    description:
      - 'A tag that will cycle through all the'
      - 'colors of the rainbow.'
    permission: 'eternaltags.tag.animatedrainbow'
  animatedGradient:
    name: 'AnimatedGradient'
    tag: '&7[<g#10:#ED213A:#93291E>AnimatedGradient&7]'
    description:
      - 'A tag that will cycle through all the'
      - 'colors of the gradient'
    permission: 'eternaltags.tag.animatedgradient'